### ISSUE TITLE
An exiting work!!! Can't wait for your code!

### ISSUE THREAD

**Issue by DLwbm123** [uncbiag/registration#1]

**Comment by marcniethammer** [comment]
Sorry, we got a little delayed. But we will make all code available in the near future. Thanks for your interest.

**Comment by A1exy** [comment]
When will the code be released? @marcniethammer

**Comment by marcniethammer** [comment]
Working on it right now. The optimization-based code is pretty close. We are working on the documentation at the moment. The deep-network parts are all implemented, but need some cleanup. Hopefully soonish.

**Comment by marcniethammer** [comment]
Sorry about the delay. We just tried to make it reasonably nice. It is now all public (see links on the main github page here).
