### ISSUE TITLE
Almost how much time need to publish this code?

### ISSUE THREAD

**Issue by hfahad** [uncbiag/registration#2]

**Comment by hbgtjxzbbx** [comment]
Sorry for the delay. Marc and I (on an intern) are both busy this summer .....
It was almost done. The project itself is not a small one, we are still improving the structures and documents. We will discuss if a previewed version should be released in weeks. Thanks for the patience.

**Comment by marcniethammer** [comment]
Sorry about the delay. We just tried to make it reasonably nice. It is now all public (see links on the main github page here).
